### ISSUE TITLE
Problem Json File

### ISSUE THREAD

**Issue by alaa-bourouissi** [Vintharas/ngstockholm-angular2-workshop#2]
In the web browser , the console : EXCEPTION: SyntaxError: JSON.parse: unexpected character at line 2 column 1 of the JSON data , is there any problem with the json file ????

**Comment by vintharas** [comment]
Fixed here https://github.com/Vintharas/angular2-step-by-step-06-consuming-real-data-with-http by adding 'accept' header to http request ^_^

**Comment by alaa-bourouissi** [comment]
Good morning Jaime ,
I have tried this example and it works fine , thank you very much .
One other question , is example is valid for the current version of angular
or not , in the future i will face some problems or not ????

2016-07-31 22:33 GMT+01:00 Jaime notifications@github.com:

**Comment by vintharas** [comment]
This example is in the beta version but I have written new samples in the latest version here:

https://github.com/Vintharas/angular2-step-by-step-01-your-first-component
https://github.com/Vintharas/angular2-step-by-step-02-refactoring-to-services
https://github.com/Vintharas/angular2-step-by-step-03-your-second-component-and-data-bindings
https://github.com/Vintharas/angular2-step-by-step-04-routing
https://github.com/Vintharas/angular2-step-by-step-05-forms-and-validation
https://github.com/Vintharas/angular2-step-by-step-06-consuming-real-data-with-http
